language: node_js

node_js:
  - "0.10"
  - "0.12"
  - "stable"
script:
  - gulp test --js=tests/create_and_get.js
  - gulp test --js=tests/entry.js
  - gulp test --js=tests/tree.js
  - gulp test --js=tests/latest.js
